[package]
name = "perft"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
liberty_chess = {workspace = true}
threadpool = {workspace = true}

[features]
default = ["parallel"]
parallel = []
