[package]
name = "ulci"
version = "0.2.2"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
liberty_chess = {workspace = true}
parking_lot = {workspace = true}
