[package]
name = "tester"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
liberty_chess = {workspace = true}
rand = {workspace = true}
ulci = {workspace = true}
