[package]
name = "liberty_chess_gui"
version = "0.13.1"
authors.workspace = true
edition.workspace = true

[dependencies]
liberty_chess = {workspace = true}
clipboard = {workspace = true, optional = true}
eframe = {workspace = true}
enum-iterator = {workspace = true}
resvg = {workspace = true}
soloud = {workspace = true, optional = true}
tiny-skia = {workspace = true}

[features]
default = ["clipboard", "clock", "sound"]
clipboard = ["dep:clipboard"]
clock = []
sound = ["dep:soloud"]
