[package]
name = "liberty_chess_gui"
version = "0.5.0"
authors.workspace = true
edition.workspace = true

[dependencies]
liberty_chess = {workspace = true}
eframe = {workspace = true}
enum-iterator = {workspace = true}
resvg = {workspace = true}
tiny-skia = {workspace = true}
usvg = {workspace = true}
