name: Compile

on:
 - push
 - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install alsa
      run: sudo apt update; sudo apt install libasound2-dev
    - name: Build
      run: cargo build --release -p liberty_chess_gui
    - uses: actions/upload-artifact@v4
      with:
        name: liberty-chess-gui
        path: target/release/liberty_chess_gui
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release -p liberty_chess_gui
    - uses: actions/upload-artifact@v4
      with:
        name: liberty-chess-gui-windows
        path: target/release/liberty_chess_gui.exe
  oxidation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --bin oxidation
    - uses: actions/upload-artifact@v4
      with:
        name: oxidation
        path: target/release/oxidation
  oxidation_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --bin oxidation
    - uses: actions/upload-artifact@v4
      with:
        name: oxidation-windows
        path: target/release/oxidation.exe
